version: '3.8'

services:
  # Server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: tortalk-server
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - tortalk-network

  # Client service
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tortalk-client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - tortalk-network

# Define a network for the services
networks:
  tortalk-network:
    driver: bridge 